### ISSUE TITLE
[Bug]: failed to spawn! Error:

### ISSUE THREAD

**Issue by Sunekaer** [someaddons/dungeonbosses#23]
### Describe the bug you're experiencing

Error below being spammed in log

### Reproducability

[30Apr2022 16:05:55.551] [Worker-Main-2/ERROR] [com.brutalbosses.BrutalBosses/]: Boss: brutalbosses:zombietoxicboss failed to spawn! Error:
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128441_(String)" because "this.creationData" is null
	at com.brutalbosses.entity.BossType.createBossEntity(BossType.java:79) ~[brutalbosses-1.18.2-4.6.jar%2364!/:1.18.2-4.6]
	at com.brutalbosses.entity.BossSpawnHandler.spawnBoss(BossSpawnHandler.java:65) ~[brutalbosses-1.18.2-4.6.jar%2364!/:1.18.2-4.6]
	at com.brutalbosses.entity.BossSpawnHandler.onChestPlaced(BossSpawnHandler.java:48) ~[brutalbosses-1.18.2-4.6.jar%2364!/:1.18.2-4.6]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.handler$zih000$onSetLoot(RandomizableContainerBlockEntity.java:534) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_59626_(RandomizableContainerBlockEntity.java:89) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.block.entity.RandomizableContainerBlockEntity.m_59620_(RandomizableContainerBlockEntity.java:42) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.m_142674_(MonsterRoomFeature.java:110) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2324!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [server-1.18.2-20220404.173914-srg.jar%23254!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs and Datapacks

.

**Comment by someaddons** [comment]
fixed in v4.7
