### ISSUE TITLE
Are you able to see whats wrong with this boss?

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/dungeonbosses#67]
```
{
  "entity": "rottencreatures:mummy",
  "entitynbt": "MobEnchantData: {EnchantType: \"NORMAL\", StoredMobEnchants: [{EnchantLevel: 10, MobEnchant: \"enchantwithmob:protection\"}], FromOwner: 0b}",
  "name": "Ama'ahat, The Undying",
  "visualscale": 1.1,
  "experience": 300,
  "protect_treasure": true,
  "effects": {
    "cofh_core:shocked": 1
  },
  "attributes": {
    "generic.max_health": 300,
    "generic.follow_range": 32,
    "generic.attack_damage": 6,
    "generic.knockback_resistance": 0.5
  },
  "customattributes": {
    "attack_speed": 0.75
  },
  "gear": {
    "mainhand": "{id: \"l2complements:totemic_gold_sword\", Count: 1b, tag: {RepairCost: 1, Damage: 0, ArmourersWorkshop: {SkinType: \"armourers:sword\", Identifier: \"db:Q1rw8CGJxq\"}, Enchantments: [{lvl: 3s, id: \"dungeons_gear:committed\"}]}}",
    "offhand": "{id: \"minecraft:shield\", Count: 1b, tag: {\"quark:RuneAttached\": 1b, BlockEntityTag: {id: \"minecraft:banner\", Patterns: [{Pattern: \"bs\", Color: 15}, {Pattern: \"sc\", Color: 4}, {Pattern: \"sku\", Color: 15}, {Pattern: \"sku\", Color: 4}, {Pattern: \"mc\", Color: 15}, {Pattern: \"bo\", Color: 4}, {Pattern: \"ts\", Color: 15}, {Pattern: \"cbo\", Color: 15}], Base: 4}, Enchantments: [{lvl: 1s, id: \"majruszsenchantments:immortality\"}, {lvl: 5s, id: \"apotheosis:shield_bash\"}], \"quark:RuneColor\": {ForgeCaps: {\"dungeons_libraries:built_in_enchantments\": {}}, id: \"quark:yellow_rune\", Count: 1b}, Damage: 0}}",
    "helmet": "{id: \"minecraft:player_head\", Count: 1b, tag: {\"quark:RuneAttached\": 1b, SkullOwner: {Properties: {textures: [{Value: \"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM0ZGU0NmIzNWJmYjc5NDE4ZTk2NjMzZjRhMWE5YmI1NTQ3YzhlYWQ2YmI4NGQ4MWIyZGUzYjFjZDFiZWMifX19\"}]}, Id: [I; -1900689272, -6733217, -1787221462, -2041823133]}, display: {Name: '{\"text\":\"Pharaoh\"}'}, Enchantments: [{lvl: 1s, id: \"minecraft:unbreaking\"}], \"quark:RuneColor\": {ForgeCaps: {\"dungeons_libraries:built_in_enchantments\": {}}, id: \"quark:yellow_rune\", Count: 1b}}}",
    "chestplate": "{id: \"l2complements:totemic_gold_chestplate\", Count: 1b, tag: {\"quark:RuneAttached\": 1b, Damage: 0, Enchantments: [{lvl: 5s, id: \"minecraft:protection\"}], \"quark:RuneColor\": {ForgeCaps: {\"dungeons_libraries:built_in_enchantments\": {}}, id: \"quark:yellow_rune\", Count: 3b}}}",
    "leggings": "{id: \"l2complements:totemic_gold_leggings\", Count: 1b, tag: {\"quark:RuneAttached\": 1b, Damage: 0, Enchantments: [{lvl: 2s, id: \"dungeons_gear:speed_aura\"}], \"quark:RuneColor\": {ForgeCaps: {\"dungeons_libraries:built_in_enchantments\": {}}, id: \"quark:yellow_rune\", Count: 1b}}}",
    "feet": "{id: \"l2complements:totemic_gold_boots\", Count: 1b, tag: {\"quark:RuneAttached\": 1b, Damage: 0, Enchantments: [{lvl: 5s, id: \"minecraft:feather_falling\"}], \"quark:RuneColor\": {ForgeCaps: {\"dungeons_libraries:built_in_enchantments\": {}}, id: \"quark:yellow_rune\", Count: 1b}}}"
  },
  "ai-goals": {
    "brutalbosses:shieldmelee": {},
    "brutalbosses:aftercombatregen": {
      "amount": 5
    }
  },
  "spawnatchest": {
    "betterdeserttemples:chests/pharaoh_hidden": 1
  }
}
```

Can you tell me what I'm doing wrong? I can't seem to spawn this boss using the commands ingame. I used the get data command provided in the documentation to extract the exact nbt data of the items and then just escaped all the quotation marks with a slash as I figured I'm meant to do otherwise the strings don't work.

But if you can't figure out whats wrong... can you implement some kind of parsing checker error reporting for when a boss file fails to validate for any particular reason so that these kind of issues are easier to track down? :V Something similar to what origins would do when an origin file fails to work.

I check the debug.log and all I get is:
```
[03Oct2023 07:24:07.820] [Render thread/WARN] [com.brutalbosses.BrutalBosses/]: Could not parse boss for:brutalbosses:huskboss
java.lang.RuntimeException: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '{' at position 0: <--[HERE]
	at com.brutalbosses.entity.BossJsonListener.tryParse(BossJsonListener.java:145) ~[brutalbosses-1.19.2-6.3.jar%23522!/:1.19.2-6.3]
	at com.brutalbosses.entity.BossJsonListener.apply(BossJsonListener.java:88) ~[brutalbosses-1.19.2-6.3.jar%23522!/:1.19.2-6.3]
	at com.brutalbosses.entity.BossJsonListener.m_5787_(BossJsonListener.java:30) ~[brutalbosses-1.19.2-6.3.jar%23522!/:1.19.2-6.3]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5419) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.doLoadLevel(WorldOpenFlows.java:148) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233145_(WorldOpenFlows.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233133_(WorldOpenFlows.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:586) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:448) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:375) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:336) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:222) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23811!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```
which seems busted, cause literally the first thing is an open curly bracket, so I'm not sure what it expects of me.

**Comment by someaddons** [comment]
the data in entitynbt needs to be enclosed in curly braces {MobEnchantData:...}
